name: Deploy Phaser game to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install deps
        working-directory: phaser-game
        run: npm ci

      - name: Build
        working-directory: phaser-game
        run: npm run build

      # Put the built site under gh-pages/phaser-game/
      - name: Stage site under subfolder
        run: |
          rm -rf gh-pages
          mkdir -p gh-pages/phaser-game
          cp -r phaser-game/dist/* gh-pages/phaser-game/

      - name: Upload artifact (gh-pages)
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
